# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bankworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bankworld.proto',
  package='bankworld',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x62\x61nkworld.proto\x12\tbankworld\"\x1c\n\rBranchRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"!\n\x0b\x42ranchReply\x12\x12\n\nbranch_msg\x18\x01 \x01(\t\"\x1d\n\x0e\x42\x61lanceRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1f\n\x0c\x42\x61lanceReply\x12\x0f\n\x07get_msg\x18\x01 \x01(\t\"\x1c\n\x08StubDone\x12\x10\n\x08stub_msg\x18\x01 \x01(\t\"\x1f\n\tStubEvent\x12\x12\n\nstub_event\x18\x01 \x01(\t2\x83\x01\n\x08\x43ustomer\x12\x39\n\ncreateStub\x12\x14.bankworld.StubEvent\x1a\x13.bankworld.StubDone\"\x00\x12<\n\rexecuteEvents\x12\x14.bankworld.StubEvent\x1a\x13.bankworld.StubDone\"\x00\x32\xcb\x01\n\x06\x42ranch\x12\x39\n\ncreateStub\x12\x14.bankworld.StubEvent\x1a\x13.bankworld.StubDone\"\x00\x12\x41\n\x0bMsgDelivery\x12\x18.bankworld.BranchRequest\x1a\x16.bankworld.BranchReply\"\x00\x12\x43\n\x0bGet_Balance\x12\x19.bankworld.BalanceRequest\x1a\x17.bankworld.BalanceReply\"\x00\x62\x06proto3'
)




_BRANCHREQUEST = _descriptor.Descriptor(
  name='BranchRequest',
  full_name='bankworld.BranchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='bankworld.BranchRequest.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=58,
)


_BRANCHREPLY = _descriptor.Descriptor(
  name='BranchReply',
  full_name='bankworld.BranchReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='branch_msg', full_name='bankworld.BranchReply.branch_msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=93,
)


_BALANCEREQUEST = _descriptor.Descriptor(
  name='BalanceRequest',
  full_name='bankworld.BalanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='bankworld.BalanceRequest.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=124,
)


_BALANCEREPLY = _descriptor.Descriptor(
  name='BalanceReply',
  full_name='bankworld.BalanceReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='get_msg', full_name='bankworld.BalanceReply.get_msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=157,
)


_STUBDONE = _descriptor.Descriptor(
  name='StubDone',
  full_name='bankworld.StubDone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stub_msg', full_name='bankworld.StubDone.stub_msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=187,
)


_STUBEVENT = _descriptor.Descriptor(
  name='StubEvent',
  full_name='bankworld.StubEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stub_event', full_name='bankworld.StubEvent.stub_event', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=220,
)

DESCRIPTOR.message_types_by_name['BranchRequest'] = _BRANCHREQUEST
DESCRIPTOR.message_types_by_name['BranchReply'] = _BRANCHREPLY
DESCRIPTOR.message_types_by_name['BalanceRequest'] = _BALANCEREQUEST
DESCRIPTOR.message_types_by_name['BalanceReply'] = _BALANCEREPLY
DESCRIPTOR.message_types_by_name['StubDone'] = _STUBDONE
DESCRIPTOR.message_types_by_name['StubEvent'] = _STUBEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BranchRequest = _reflection.GeneratedProtocolMessageType('BranchRequest', (_message.Message,), {
  'DESCRIPTOR' : _BRANCHREQUEST,
  '__module__' : 'bankworld_pb2'
  # @@protoc_insertion_point(class_scope:bankworld.BranchRequest)
  })
_sym_db.RegisterMessage(BranchRequest)

BranchReply = _reflection.GeneratedProtocolMessageType('BranchReply', (_message.Message,), {
  'DESCRIPTOR' : _BRANCHREPLY,
  '__module__' : 'bankworld_pb2'
  # @@protoc_insertion_point(class_scope:bankworld.BranchReply)
  })
_sym_db.RegisterMessage(BranchReply)

BalanceRequest = _reflection.GeneratedProtocolMessageType('BalanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _BALANCEREQUEST,
  '__module__' : 'bankworld_pb2'
  # @@protoc_insertion_point(class_scope:bankworld.BalanceRequest)
  })
_sym_db.RegisterMessage(BalanceRequest)

BalanceReply = _reflection.GeneratedProtocolMessageType('BalanceReply', (_message.Message,), {
  'DESCRIPTOR' : _BALANCEREPLY,
  '__module__' : 'bankworld_pb2'
  # @@protoc_insertion_point(class_scope:bankworld.BalanceReply)
  })
_sym_db.RegisterMessage(BalanceReply)

StubDone = _reflection.GeneratedProtocolMessageType('StubDone', (_message.Message,), {
  'DESCRIPTOR' : _STUBDONE,
  '__module__' : 'bankworld_pb2'
  # @@protoc_insertion_point(class_scope:bankworld.StubDone)
  })
_sym_db.RegisterMessage(StubDone)

StubEvent = _reflection.GeneratedProtocolMessageType('StubEvent', (_message.Message,), {
  'DESCRIPTOR' : _STUBEVENT,
  '__module__' : 'bankworld_pb2'
  # @@protoc_insertion_point(class_scope:bankworld.StubEvent)
  })
_sym_db.RegisterMessage(StubEvent)



_CUSTOMER = _descriptor.ServiceDescriptor(
  name='Customer',
  full_name='bankworld.Customer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=223,
  serialized_end=354,
  methods=[
  _descriptor.MethodDescriptor(
    name='createStub',
    full_name='bankworld.Customer.createStub',
    index=0,
    containing_service=None,
    input_type=_STUBEVENT,
    output_type=_STUBDONE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='executeEvents',
    full_name='bankworld.Customer.executeEvents',
    index=1,
    containing_service=None,
    input_type=_STUBEVENT,
    output_type=_STUBDONE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CUSTOMER)

DESCRIPTOR.services_by_name['Customer'] = _CUSTOMER


_BRANCH = _descriptor.ServiceDescriptor(
  name='Branch',
  full_name='bankworld.Branch',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=357,
  serialized_end=560,
  methods=[
  _descriptor.MethodDescriptor(
    name='createStub',
    full_name='bankworld.Branch.createStub',
    index=0,
    containing_service=None,
    input_type=_STUBEVENT,
    output_type=_STUBDONE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MsgDelivery',
    full_name='bankworld.Branch.MsgDelivery',
    index=1,
    containing_service=None,
    input_type=_BRANCHREQUEST,
    output_type=_BRANCHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Get_Balance',
    full_name='bankworld.Branch.Get_Balance',
    index=2,
    containing_service=None,
    input_type=_BALANCEREQUEST,
    output_type=_BALANCEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BRANCH)

DESCRIPTOR.services_by_name['Branch'] = _BRANCH

# @@protoc_insertion_point(module_scope)
