# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bankworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bankworld.proto',
  package='bankworld',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x62\x61nkworld.proto\x12\tbankworld\"\x1c\n\rBranchRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"!\n\x0b\x42ranchReply\x12\x12\n\nbranch_msg\x18\x01 \x01(\t\"\x1e\n\x0fWithdrawRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"%\n\rWithdrawReply\x12\x14\n\x0cwithdraw_msg\x18\x01 \x01(\t\"\x1d\n\x0e\x44\x65positRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"#\n\x0c\x44\x65positReply\x12\x13\n\x0b\x64\x65posit_msg\x18\x01 \x01(\t\"\x1c\n\x08StubDone\x12\x10\n\x08stub_msg\x18\x01 \x01(\t\"\x1f\n\tStubEvent\x12\x12\n\nstub_event\x18\x01 \x01(\t2\x83\x01\n\x08\x43ustomer\x12\x39\n\ncreateStub\x12\x14.bankworld.StubEvent\x1a\x13.bankworld.StubDone\"\x00\x12<\n\rexecuteEvents\x12\x14.bankworld.StubEvent\x1a\x13.bankworld.StubDone\"\x00\x32\x9f\x02\n\x06\x42ranch\x12\x39\n\ncreateStub\x12\x14.bankworld.StubEvent\x1a\x13.bankworld.StubDone\"\x00\x12\x41\n\x0bMsgDelivery\x12\x18.bankworld.BranchRequest\x1a\x16.bankworld.BranchReply\"\x00\x12L\n\x12Propagate_Withdraw\x12\x1a.bankworld.WithdrawRequest\x1a\x18.bankworld.WithdrawReply\"\x00\x12I\n\x11Propagate_Deposit\x12\x19.bankworld.DepositRequest\x1a\x17.bankworld.DepositReply\"\x00\x62\x06proto3'
)




_BRANCHREQUEST = _descriptor.Descriptor(
  name='BranchRequest',
  full_name='bankworld.BranchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='bankworld.BranchRequest.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=58,
)


_BRANCHREPLY = _descriptor.Descriptor(
  name='BranchReply',
  full_name='bankworld.BranchReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='branch_msg', full_name='bankworld.BranchReply.branch_msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=93,
)


_WITHDRAWREQUEST = _descriptor.Descriptor(
  name='WithdrawRequest',
  full_name='bankworld.WithdrawRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='bankworld.WithdrawRequest.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=125,
)


_WITHDRAWREPLY = _descriptor.Descriptor(
  name='WithdrawReply',
  full_name='bankworld.WithdrawReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='withdraw_msg', full_name='bankworld.WithdrawReply.withdraw_msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=164,
)


_DEPOSITREQUEST = _descriptor.Descriptor(
  name='DepositRequest',
  full_name='bankworld.DepositRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='bankworld.DepositRequest.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=195,
)


_DEPOSITREPLY = _descriptor.Descriptor(
  name='DepositReply',
  full_name='bankworld.DepositReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deposit_msg', full_name='bankworld.DepositReply.deposit_msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=232,
)


_STUBDONE = _descriptor.Descriptor(
  name='StubDone',
  full_name='bankworld.StubDone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stub_msg', full_name='bankworld.StubDone.stub_msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=262,
)


_STUBEVENT = _descriptor.Descriptor(
  name='StubEvent',
  full_name='bankworld.StubEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stub_event', full_name='bankworld.StubEvent.stub_event', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=295,
)

DESCRIPTOR.message_types_by_name['BranchRequest'] = _BRANCHREQUEST
DESCRIPTOR.message_types_by_name['BranchReply'] = _BRANCHREPLY
DESCRIPTOR.message_types_by_name['WithdrawRequest'] = _WITHDRAWREQUEST
DESCRIPTOR.message_types_by_name['WithdrawReply'] = _WITHDRAWREPLY
DESCRIPTOR.message_types_by_name['DepositRequest'] = _DEPOSITREQUEST
DESCRIPTOR.message_types_by_name['DepositReply'] = _DEPOSITREPLY
DESCRIPTOR.message_types_by_name['StubDone'] = _STUBDONE
DESCRIPTOR.message_types_by_name['StubEvent'] = _STUBEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BranchRequest = _reflection.GeneratedProtocolMessageType('BranchRequest', (_message.Message,), {
  'DESCRIPTOR' : _BRANCHREQUEST,
  '__module__' : 'bankworld_pb2'
  # @@protoc_insertion_point(class_scope:bankworld.BranchRequest)
  })
_sym_db.RegisterMessage(BranchRequest)

BranchReply = _reflection.GeneratedProtocolMessageType('BranchReply', (_message.Message,), {
  'DESCRIPTOR' : _BRANCHREPLY,
  '__module__' : 'bankworld_pb2'
  # @@protoc_insertion_point(class_scope:bankworld.BranchReply)
  })
_sym_db.RegisterMessage(BranchReply)

WithdrawRequest = _reflection.GeneratedProtocolMessageType('WithdrawRequest', (_message.Message,), {
  'DESCRIPTOR' : _WITHDRAWREQUEST,
  '__module__' : 'bankworld_pb2'
  # @@protoc_insertion_point(class_scope:bankworld.WithdrawRequest)
  })
_sym_db.RegisterMessage(WithdrawRequest)

WithdrawReply = _reflection.GeneratedProtocolMessageType('WithdrawReply', (_message.Message,), {
  'DESCRIPTOR' : _WITHDRAWREPLY,
  '__module__' : 'bankworld_pb2'
  # @@protoc_insertion_point(class_scope:bankworld.WithdrawReply)
  })
_sym_db.RegisterMessage(WithdrawReply)

DepositRequest = _reflection.GeneratedProtocolMessageType('DepositRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEPOSITREQUEST,
  '__module__' : 'bankworld_pb2'
  # @@protoc_insertion_point(class_scope:bankworld.DepositRequest)
  })
_sym_db.RegisterMessage(DepositRequest)

DepositReply = _reflection.GeneratedProtocolMessageType('DepositReply', (_message.Message,), {
  'DESCRIPTOR' : _DEPOSITREPLY,
  '__module__' : 'bankworld_pb2'
  # @@protoc_insertion_point(class_scope:bankworld.DepositReply)
  })
_sym_db.RegisterMessage(DepositReply)

StubDone = _reflection.GeneratedProtocolMessageType('StubDone', (_message.Message,), {
  'DESCRIPTOR' : _STUBDONE,
  '__module__' : 'bankworld_pb2'
  # @@protoc_insertion_point(class_scope:bankworld.StubDone)
  })
_sym_db.RegisterMessage(StubDone)

StubEvent = _reflection.GeneratedProtocolMessageType('StubEvent', (_message.Message,), {
  'DESCRIPTOR' : _STUBEVENT,
  '__module__' : 'bankworld_pb2'
  # @@protoc_insertion_point(class_scope:bankworld.StubEvent)
  })
_sym_db.RegisterMessage(StubEvent)



_CUSTOMER = _descriptor.ServiceDescriptor(
  name='Customer',
  full_name='bankworld.Customer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=298,
  serialized_end=429,
  methods=[
  _descriptor.MethodDescriptor(
    name='createStub',
    full_name='bankworld.Customer.createStub',
    index=0,
    containing_service=None,
    input_type=_STUBEVENT,
    output_type=_STUBDONE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='executeEvents',
    full_name='bankworld.Customer.executeEvents',
    index=1,
    containing_service=None,
    input_type=_STUBEVENT,
    output_type=_STUBDONE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CUSTOMER)

DESCRIPTOR.services_by_name['Customer'] = _CUSTOMER


_BRANCH = _descriptor.ServiceDescriptor(
  name='Branch',
  full_name='bankworld.Branch',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=432,
  serialized_end=719,
  methods=[
  _descriptor.MethodDescriptor(
    name='createStub',
    full_name='bankworld.Branch.createStub',
    index=0,
    containing_service=None,
    input_type=_STUBEVENT,
    output_type=_STUBDONE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MsgDelivery',
    full_name='bankworld.Branch.MsgDelivery',
    index=1,
    containing_service=None,
    input_type=_BRANCHREQUEST,
    output_type=_BRANCHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Propagate_Withdraw',
    full_name='bankworld.Branch.Propagate_Withdraw',
    index=2,
    containing_service=None,
    input_type=_WITHDRAWREQUEST,
    output_type=_WITHDRAWREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Propagate_Deposit',
    full_name='bankworld.Branch.Propagate_Deposit',
    index=3,
    containing_service=None,
    input_type=_DEPOSITREQUEST,
    output_type=_DEPOSITREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BRANCH)

DESCRIPTOR.services_by_name['Branch'] = _BRANCH

# @@protoc_insertion_point(module_scope)
