# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bankworld_pb2 as bankworld__pb2


class CustomerStub(object):
    """The customer service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createStub = channel.unary_unary(
                '/bankworld.Customer/createStub',
                request_serializer=bankworld__pb2.StubEvent.SerializeToString,
                response_deserializer=bankworld__pb2.StubDone.FromString,
                )
        self.executeEvents = channel.unary_unary(
                '/bankworld.Customer/executeEvents',
                request_serializer=bankworld__pb2.StubEvent.SerializeToString,
                response_deserializer=bankworld__pb2.StubDone.FromString,
                )


class CustomerServicer(object):
    """The customer service definition.
    """

    def createStub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def executeEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createStub': grpc.unary_unary_rpc_method_handler(
                    servicer.createStub,
                    request_deserializer=bankworld__pb2.StubEvent.FromString,
                    response_serializer=bankworld__pb2.StubDone.SerializeToString,
            ),
            'executeEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.executeEvents,
                    request_deserializer=bankworld__pb2.StubEvent.FromString,
                    response_serializer=bankworld__pb2.StubDone.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bankworld.Customer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Customer(object):
    """The customer service definition.
    """

    @staticmethod
    def createStub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bankworld.Customer/createStub',
            bankworld__pb2.StubEvent.SerializeToString,
            bankworld__pb2.StubDone.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def executeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bankworld.Customer/executeEvents',
            bankworld__pb2.StubEvent.SerializeToString,
            bankworld__pb2.StubDone.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class BranchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createStub = channel.unary_unary(
                '/bankworld.Branch/createStub',
                request_serializer=bankworld__pb2.StubEvent.SerializeToString,
                response_deserializer=bankworld__pb2.StubDone.FromString,
                )
        self.MsgDelivery = channel.unary_unary(
                '/bankworld.Branch/MsgDelivery',
                request_serializer=bankworld__pb2.BranchRequest.SerializeToString,
                response_deserializer=bankworld__pb2.BranchReply.FromString,
                )
        self.Propagate_Withdraw = channel.unary_unary(
                '/bankworld.Branch/Propagate_Withdraw',
                request_serializer=bankworld__pb2.WithdrawRequest.SerializeToString,
                response_deserializer=bankworld__pb2.WithdrawReply.FromString,
                )
        self.Propagate_Deposit = channel.unary_unary(
                '/bankworld.Branch/Propagate_Deposit',
                request_serializer=bankworld__pb2.DepositRequest.SerializeToString,
                response_deserializer=bankworld__pb2.DepositReply.FromString,
                )


class BranchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createStub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MsgDelivery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Propagate_Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Propagate_Deposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BranchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createStub': grpc.unary_unary_rpc_method_handler(
                    servicer.createStub,
                    request_deserializer=bankworld__pb2.StubEvent.FromString,
                    response_serializer=bankworld__pb2.StubDone.SerializeToString,
            ),
            'MsgDelivery': grpc.unary_unary_rpc_method_handler(
                    servicer.MsgDelivery,
                    request_deserializer=bankworld__pb2.BranchRequest.FromString,
                    response_serializer=bankworld__pb2.BranchReply.SerializeToString,
            ),
            'Propagate_Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Propagate_Withdraw,
                    request_deserializer=bankworld__pb2.WithdrawRequest.FromString,
                    response_serializer=bankworld__pb2.WithdrawReply.SerializeToString,
            ),
            'Propagate_Deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.Propagate_Deposit,
                    request_deserializer=bankworld__pb2.DepositRequest.FromString,
                    response_serializer=bankworld__pb2.DepositReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bankworld.Branch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Branch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createStub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bankworld.Branch/createStub',
            bankworld__pb2.StubEvent.SerializeToString,
            bankworld__pb2.StubDone.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MsgDelivery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bankworld.Branch/MsgDelivery',
            bankworld__pb2.BranchRequest.SerializeToString,
            bankworld__pb2.BranchReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Propagate_Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bankworld.Branch/Propagate_Withdraw',
            bankworld__pb2.WithdrawRequest.SerializeToString,
            bankworld__pb2.WithdrawReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Propagate_Deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bankworld.Branch/Propagate_Deposit',
            bankworld__pb2.DepositRequest.SerializeToString,
            bankworld__pb2.DepositReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
